# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindowUI.ui'
#
# Created: Thu May 30 00:31:53 2013
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_mainWindowPVFX(object):
    def setupUi(self, mainWindowPVFX):
        mainWindowPVFX.setObjectName(_fromUtf8("mainWindowPVFX"))
        mainWindowPVFX.resize(1148, 786)
        self.centralwidget = QtGui.QWidget(mainWindowPVFX)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_8 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.groupBoxCentral = QtGui.QGroupBox(self.centralwidget)
        self.groupBoxCentral.setTitle(_fromUtf8(""))
        self.groupBoxCentral.setObjectName(_fromUtf8("groupBoxCentral"))
        self.gridLayout_5 = QtGui.QGridLayout(self.groupBoxCentral)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.splitterPipeline = QtGui.QSplitter(self.groupBoxCentral)
        self.splitterPipeline.setOrientation(QtCore.Qt.Vertical)
        self.splitterPipeline.setObjectName(_fromUtf8("splitterPipeline"))
        self.groupBoxPipeline = QtGui.QGroupBox(self.splitterPipeline)
        self.groupBoxPipeline.setObjectName(_fromUtf8("groupBoxPipeline"))
        self.gridLayoutPipeline = QtGui.QGridLayout(self.groupBoxPipeline)
        self.gridLayoutPipeline.setObjectName(_fromUtf8("gridLayoutPipeline"))
        self.splitterCentral = QtGui.QSplitter(self.splitterPipeline)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitterCentral.sizePolicy().hasHeightForWidth())
        self.splitterCentral.setSizePolicy(sizePolicy)
        self.splitterCentral.setOrientation(QtCore.Qt.Horizontal)
        self.splitterCentral.setObjectName(_fromUtf8("splitterCentral"))
        self.groupBoxPj = QtGui.QGroupBox(self.splitterCentral)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBoxPj.sizePolicy().hasHeightForWidth())
        self.groupBoxPj.setSizePolicy(sizePolicy)
        self.groupBoxPj.setObjectName(_fromUtf8("groupBoxPj"))
        self.gridLayout = QtGui.QGridLayout(self.groupBoxPj)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label = QtGui.QLabel(self.groupBoxPj)
        self.label.setPixmap(QtGui.QPixmap(_fromUtf8(":/images/other1/H_zoom.png")))
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        self.lineEditSearch = QtGui.QLineEdit(self.groupBoxPj)
        self.lineEditSearch.setObjectName(_fromUtf8("lineEditSearch"))
        self.horizontalLayout.addWidget(self.lineEditSearch)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.listViewPj = QtGui.QListView(self.groupBoxPj)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listViewPj.sizePolicy().hasHeightForWidth())
        self.listViewPj.setSizePolicy(sizePolicy)
        self.listViewPj.setObjectName(_fromUtf8("listViewPj"))
        self.gridLayout.addWidget(self.listViewPj, 1, 0, 1, 1)
        self.groupBoxApp = QtGui.QGroupBox(self.splitterCentral)
        self.groupBoxApp.setObjectName(_fromUtf8("groupBoxApp"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBoxApp)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.splitterApp = QtGui.QSplitter(self.groupBoxApp)
        self.splitterApp.setOrientation(QtCore.Qt.Vertical)
        self.splitterApp.setObjectName(_fromUtf8("splitterApp"))
        self.tabWidgetApp = QtGui.QTabWidget(self.splitterApp)
        self.tabWidgetApp.setObjectName(_fromUtf8("tabWidgetApp"))
        self.tabSW = QtGui.QWidget()
        self.tabSW.setObjectName(_fromUtf8("tabSW"))
        self.gridLayout_3 = QtGui.QGridLayout(self.tabSW)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.groupBoxSW = QtGui.QGroupBox(self.tabSW)
        self.groupBoxSW.setObjectName(_fromUtf8("groupBoxSW"))
        self.gridLayoutSW = QtGui.QGridLayout(self.groupBoxSW)
        self.gridLayoutSW.setObjectName(_fromUtf8("gridLayoutSW"))
        self.gridLayout_3.addWidget(self.groupBoxSW, 0, 0, 1, 1)
        self.tabWidgetApp.addTab(self.tabSW, _fromUtf8(""))
        self.tab2 = QtGui.QWidget()
        self.tab2.setObjectName(_fromUtf8("tab2"))
        self.gridLayout_4 = QtGui.QGridLayout(self.tab2)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.groupBox_2 = QtGui.QGroupBox(self.tab2)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout_9 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.pushButton = QtGui.QPushButton(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.gridLayout_9.addWidget(self.pushButton, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox_2, 0, 0, 1, 1)
        self.tabWidgetApp.addTab(self.tab2, _fromUtf8(""))
        self.tabWidgetGene = QtGui.QTabWidget(self.splitterApp)
        self.tabWidgetGene.setObjectName(_fromUtf8("tabWidgetGene"))
        self.tabGene = QtGui.QWidget()
        self.tabGene.setObjectName(_fromUtf8("tabGene"))
        self.gridLayout_6 = QtGui.QGridLayout(self.tabGene)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.groupBox_4 = QtGui.QGroupBox(self.tabGene)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.checkBox = QtGui.QCheckBox(self.groupBox_4)
        self.checkBox.setGeometry(QtCore.QRect(60, 60, 71, 16))
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        self.gridLayout_6.addWidget(self.groupBox_4, 0, 0, 1, 1)
        self.tabWidgetGene.addTab(self.tabGene, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.tabWidgetGene.addTab(self.tab_4, _fromUtf8(""))
        self.gridLayout_2.addWidget(self.splitterApp, 0, 0, 1, 1)
        self.gridLayout_5.addWidget(self.splitterPipeline, 0, 0, 1, 1)
        self.gridLayout_8.addWidget(self.groupBoxCentral, 0, 0, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.pushButton_2 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.horizontalLayout_2.addWidget(self.pushButton_2)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.gridLayout_8.addLayout(self.horizontalLayout_2, 2, 0, 1, 1)
        mainWindowPVFX.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(mainWindowPVFX)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1148, 23))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuAbout = QtGui.QMenu(self.menubar)
        self.menuAbout.setObjectName(_fromUtf8("menuAbout"))
        mainWindowPVFX.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(mainWindowPVFX)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        mainWindowPVFX.setStatusBar(self.statusbar)
        self.toolBarTop = QtGui.QToolBar(mainWindowPVFX)
        self.toolBarTop.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.toolBarTop.setObjectName(_fromUtf8("toolBarTop"))
        mainWindowPVFX.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBarTop)
        self.toolBarLeft = QtGui.QToolBar(mainWindowPVFX)
        self.toolBarLeft.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolBarLeft.setObjectName(_fromUtf8("toolBarLeft"))
        mainWindowPVFX.addToolBar(QtCore.Qt.LeftToolBarArea, self.toolBarLeft)
        self.toolBarTop2 = QtGui.QToolBar(mainWindowPVFX)
        self.toolBarTop2.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.toolBarTop2.setObjectName(_fromUtf8("toolBarTop2"))
        mainWindowPVFX.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBarTop2)
        self.actionAbout = QtGui.QAction(mainWindowPVFX)
        self.actionAbout.setEnabled(True)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/vfx.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAbout.setIcon(icon)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.actionPre = QtGui.QAction(mainWindowPVFX)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/other1/confg_out.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPre.setIcon(icon1)
        self.actionPre.setObjectName(_fromUtf8("actionPre"))
        self.actionQuit = QtGui.QAction(mainWindowPVFX)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/other1/back_out.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionQuit.setIcon(icon2)
        self.actionQuit.setObjectName(_fromUtf8("actionQuit"))
        self.actionLog = QtGui.QAction(mainWindowPVFX)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/other1/layer.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionLog.setIcon(icon3)
        self.actionLog.setObjectName(_fromUtf8("actionLog"))
        self.menuAbout.addAction(self.actionAbout)
        self.menuAbout.addSeparator()
        self.menuAbout.addAction(self.actionPre)
        self.menuAbout.addSeparator()
        self.menuAbout.addAction(self.actionLog)
        self.menuAbout.addSeparator()
        self.menuAbout.addAction(self.actionQuit)
        self.menubar.addAction(self.menuAbout.menuAction())
        self.toolBarTop.addAction(self.actionAbout)
        self.toolBarTop.addAction(self.actionPre)
        self.toolBarTop.addAction(self.actionLog)
        self.toolBarLeft.addAction(self.actionPre)
        self.toolBarLeft.addAction(self.actionLog)
        self.toolBarTop2.addAction(self.actionQuit)

        self.retranslateUi(mainWindowPVFX)
        self.tabWidgetApp.setCurrentIndex(0)
        self.tabWidgetGene.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(mainWindowPVFX)

    def retranslateUi(self, mainWindowPVFX):
        mainWindowPVFX.setWindowTitle(_translate("mainWindowPVFX", "projectVFX", None))
        self.groupBoxPipeline.setTitle(_translate("mainWindowPVFX", "Pipeline", None))
        self.groupBoxPj.setTitle(_translate("mainWindowPVFX", "Project", None))
        self.groupBoxApp.setTitle(_translate("mainWindowPVFX", "Application", None))
        self.groupBoxSW.setTitle(_translate("mainWindowPVFX", "Software", None))
        self.tabWidgetApp.setTabText(self.tabWidgetApp.indexOf(self.tabSW), _translate("mainWindowPVFX", "Software", None))
        self.groupBox_2.setTitle(_translate("mainWindowPVFX", "GroupBox", None))
        self.pushButton.setText(_translate("mainWindowPVFX", "PushButton", None))
        self.tabWidgetApp.setTabText(self.tabWidgetApp.indexOf(self.tab2), _translate("mainWindowPVFX", "Tab 2", None))
        self.groupBox_4.setTitle(_translate("mainWindowPVFX", "GroupBox", None))
        self.checkBox.setText(_translate("mainWindowPVFX", "CheckBox", None))
        self.tabWidgetGene.setTabText(self.tabWidgetGene.indexOf(self.tabGene), _translate("mainWindowPVFX", "Gene", None))
        self.tabWidgetGene.setTabText(self.tabWidgetGene.indexOf(self.tab_4), _translate("mainWindowPVFX", "Tab 2", None))
        self.pushButton_2.setText(_translate("mainWindowPVFX", "PushButton", None))
        self.menuAbout.setTitle(_translate("mainWindowPVFX", "projectVFX", None))
        self.toolBarTop.setWindowTitle(_translate("mainWindowPVFX", "toolBar", None))
        self.toolBarLeft.setWindowTitle(_translate("mainWindowPVFX", "toolBar_2", None))
        self.toolBarTop2.setWindowTitle(_translate("mainWindowPVFX", "toolBar", None))
        self.actionAbout.setText(_translate("mainWindowPVFX", "About", None))
        self.actionPre.setText(_translate("mainWindowPVFX", "Preferences", None))
        self.actionQuit.setText(_translate("mainWindowPVFX", "Quit", None))
        self.actionLog.setText(_translate("mainWindowPVFX", "Log", None))

import projectVFX_ReSource_rc
